services:
  neo4j:
    build: ./neo4j
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_server_directories_import: /import
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    command: >
      sh -c "
      neo4j console & 
      until cypher-shell -u neo4j -p password 'RETURN 1;' >/dev/null 2>&1; do
          sleep 5;
      done;
      echo 'Running import...';
      cypher-shell -u neo4j -p password -f /import/import.cypher;
      wait
      "

  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ztm
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:Z
      - /app/node_modules
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:Z
      - /app/node_modules
    depends_on:
      - backend

volumes:
  neo4j_data:
  mariadb_data: